### ISSUE TITLE
Empty toolbar after upgrading to doublecmd-1.2.0-11439.cocoa.aarch64

### ISSUE THREAD

**Issue by ghost** [doublecmd/doublecmd#1821] opened 2024-09-09 05:48 UTC
### Version

Double Commander
Version: 1.2.0 alpha
Revision: 11439
Commit: 9310362d0
Build date: 2024/09/09
Lazarus: 3.99.0.0
FPC: 3.2.2
Platform: aarch64-Darwin-cocoa
OS version: Mac OS X 14.6.1

### Description

After upgrading to doublecmd-1.2.0-11439.cocoa.aarch64, the toolbar is empty.

When right-clicking the toolbar, DC crashes.

[crash_report.txt](https://github.com/user-attachments/files/16925962/crash_report.txt)

![empty_toolbar](https://github.com/user-attachments/assets/e48ac53b-cb02-45b0-bac9-55bc55da498e)

**Comment by rich2014** [comment] 2024-09-09 08:32
it  should be caused by the recent patch that hides repeated separators in Lazarus/LCL.

try the new SnapShoot please.

**Comment by rich2014** [comment] 2024-09-09 16:57
i forgot to submit the patch to Lazaurs.

i have submitted it now, test the SnapShoot again please.

**Comment by alexx2000** [comment] 2024-09-10 07:28
> And the DC icon in the dock is too large.

Was it normal before? I guess this [change](https://github.com/doublecmd/doublecmd/commit/d011b40705c8e12503c7c8eb25c9bee4de642d72) could broke it:
```
 {$IF DEFINED(DARWIN)}
   GetMacFormatSettings(DefaultFormatSettings);
-  Application.Icon:= nil;
 {$ENDIF}
```

**Comment by rich2014** [comment] 2024-09-10 16:05
@Andreas0602 

try the last snapshoot please.

**Comment by rich2014** [comment] 2024-09-10 16:53
@Andreas0602 

it works fine on my Notebook.

how many points has it been raised up?

> The problem that the position of the DC window after restart is too high is still present.

**Comment by rich2014** [comment] 2024-09-11 15:37
@Andreas0602 

fixed in Lazarus.

test the last snapshoot please.

> The problem that the position of the DC window after restart is too high is still present.

**Closed as completed** 2024-09-11 17:31 UTC
Labels: bug
