### ISSUE TITLE
Drag’n’Drop problems

### ISSUE THREAD

**Issue by t2YU2m8l83** [doublecmd/doublecmd#229] opened 2021-10-29 11:03 UTC
Despite trying a couple of different patterns, I wasn’t able to get one that reproduce the error all the time. Drag’n’droping files from DC to other programs like mediainfo, mkvmerge or notepad will work a couple of times but after that breaks for a random amount of time. Reopening new instances of 3rd party programs and drag’n’droping different files into them will speed up the process until the error occurs. The error results in nothings happening at all and DC freezing for a couple of seconds. If you’re not waiting that long and go back to DC with your mouse, a dialog that prompts to copy the files to the place your mouse went pops up. This is really annoying because it makes drag’n’drop pretty much unusable. The error didn’t happen inside my VM which only has one virtual monitor attached. But it did happen on my main system when removing two monitors. Therefore it might be some kind of special interaction between my daily windows and DC. The regular file explorer doesn't has this issue.

Double Commander
Version: 1.1.0 alpha
Revision: 9965
Commit: 78d28932a
Build date: 2021/10/28
Lazarus: 2.2.0.2
FPC: 3.2.2
Platform: x86_64-Win64-qt5
OS version: Windows 10 20H2 x86_64

Widgetset library: Qt 5.13.0, libQt5Pas 5.6.1

**Comment by WhiteChairFromIkea** [comment] 2021-10-30 19:31
Hi, this is a duplicate of https://github.com/doublecmd/doublecmd/issues/129

This bug is a real showstopper for me. I need to invoke freecommander when need to drag and drop reliably.. (made a button to open freecommander at current path..). I would assign this bug high priority, I cannot drag and drog attachements to even when writing email, simple dayly tasks are ruined :/

**Comment by alexx2000** [comment] 2021-10-30 20:59
I'm afraid that it is simpler to remove dark version than fix it.

**Closed as completed** 2022-05-02 14:32 UTC
