### ISSUE TITLE
macOS - Multi-Rename - mask "..." drop down menu actions not working e.g. [Nx:y]

### ISSUE THREAD

**Issue by 17matejka** [doublecmd/doublecmd#832] opened 2023-02-22 15:13 UTC
### Version

Double Commander
Version: 1.1.0 alpha
Revision: 10597
Commit: 8b9ac49d4
Build date: 2023/02/21
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 11.7.1

### Description

I am monitoring this issue for a while on macOS (probably since 0.9x).
When you select file/files, open _Multi Rename Tool_, in field _Mask_ - _File Name/Extension_ click on ... button and choose whatever action e.g. _[Nx:y]_, on the next window select your string, result preview shows you e.g. _[N7:13]_, you click OK and expecting to see [N7:13] in _File Name_ field but **nothing happens**.
![dc_rename_error](https://user-images.githubusercontent.com/125045285/220664481-79bb188d-b26d-43d7-885f-93e39670061c.png)

Last version without this issue that I have is:

Double Commander
Version: 0.9.10 beta
Revision: 9640
Build date: 2021/01/10
Lazarus: 2.0.3.0-61194
FPC: 3.0.4
Platform: x86_64-Darwin-qt4
OS version: Mac OS X 10.16.0

Widgetset library: Qt 4.8.6, libQt4Pas 4.5.3

**Comment by rich2014** [comment] 2023-02-25 13:34
it's caused by Lazarus (LCL Cocoa).

fixed in #834

**Closed** 2023-03-05 09:52 UTC
Labels: bug
