### ISSUE TITLE
MacOS - No response to key presses after any actions in the right panel

### ISSUE THREAD

**Issue by VicDobrov** [doublecmd/doublecmd#657] opened 2022-11-04 02:20 UTC
MacOS - Keyboard input focus is lost after any action in the right pane.
For example: go to the right panel folder, press F3 on the file, then Escape and after that the commander does not respond to all key presses, except for the function keys F1-F10. 
Only the system error sound is heard with all key presses.
This bug in beta versions of Double Commander is present on all MacOS. tested on Monterey 12.6 ... Mojave 10.14

**Comment by JonnyTech** [comment] 2022-11-04 09:39
Which build of DC first exhibits this issue?

**Comment by VicDobrov** [comment] 2022-11-04 10:51
Version 0.9.10 works fine. I don't know the exact version, I couldn't find the Beta version for Mac OS.
Nightly builds have this bug. Double Commander 1.1.0 Alpha 10408
Platform: x86_64-Darwin-cocoa OS Version: Mac OS X 10.16.0

**Comment by rich2014** [comment] 2022-11-04 13:26
can't reproduce on MacOS 12.6
can you provide a screen recording?

**Comment by VicDobrov** [comment] 2022-11-05 03:38
on MacOS (and maybe other OSes) a bug when navigating in the right panel: here is doublecmd.xml, where there are 5 tabs:

we start DC with it, we will enter in the right panel into any folder from the keyboard, that is, we do not use the mouse.
After that, DC does not respond to key presses, except for functional F1-10
the transition to the parent folder and all navigation does not work. An error system sound is heard when keys are pressed.
`<?xml version="1.0" encoding="UTF-8"?>
<doublecmd DCVersion="1.1.0 alpha" ConfigVersion="13">
  <Tabs>
    <OpenedTabs>
      <Right>
        <ActiveTab>1</ActiveTab>
        <Tab>
          <FileView Type="brief">
            <History>
              <Entry Active="True">
                <FileSource Type="FileSystem"/>
                <Paths>
                  <Path Filename="..">/Volumes/Download/</Path>
                </Paths>
              </Entry>
            </History>
          </FileView>
        </Tab>
        <Tab>
          <FileView Type="brief">
            <History>
              <Entry Active="True">
                <FileSource Type="FileSystem"/>
                <Paths>
                  <Path Filename="..">/Volumes/Download/</Path>
                </Paths>
              </Entry>
            </History>
          </FileView>
        </Tab>
        <Tab>
          <FileView Type="brief">
            <History>
              <Entry Active="True">
                <FileSource Type="FileSystem"/>
                <Paths>
                  <Path Filename="..">~/Downloads/</Path>
                </Paths>
              </Entry>
            </History>
          </FileView>
        </Tab>
        <Tab>
          <FileView Type="brief">
            <History>
              <Entry Active="True">
                <FileSource Type="FileSystem"/>
                <Paths>
                  <Path Filename="">~/Downloads/</Path>
                </Paths>
              </Entry>
            </History>
          </FileView>
        </Tab>
        <Tab>
          <FileView Type="brief">
            <History>
              <Entry Active="True">
                <FileSource Type="FileSystem"/>
                <Paths>
                  <Path Filename="">/Applications/</Path>
                </Paths>
              </Entry>
            </History>
          </FileView>
        </Tab>
      </Right>
    </OpenedTabs>
  </Tabs>
</doublecmd>`

**Comment by rich2014** [comment] 2022-11-05 08:38
confirmed, it is caused by a bug of Cocoa/TabControl in Lazaurs.
when the panel width is not enough, it will switch to the wrong Tab.
a patch has been submitted to Lazarus last month, but it has not been merged.
https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/39944

you can temporarily deal with it:
1. keep the width of the Panel enough to display all Tabs
2. focus by mouse first
3. focus by Control+Digital first

**Comment by rich2014** [comment] 2022-11-16 00:28
the PR had been merged into the main branch: https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/39944
@alexx2000 could you please rebuild with latest Lazarus version?

**Comment by alexx2000** [comment] 2022-11-17 05:23
Yes, I can. But cross-compilation problem is not solved #642

**Comment by alexx2000** [comment] 2022-11-17 19:16
Done, see #642

**Comment by rich2014** [comment] 2023-04-10 14:16
#657 should be closed.

**Closed** 2023-04-10 15:40 UTC
