### ISSUE TITLE
EZeroDivide: Floating point division by zero

### ISSUE THREAD

**Issue by davouch** [doublecmd/doublecmd#235] opened 2021-10-31 11:20 UTC
--------------- 31-10-2021, 11:52:57 ---------------
| DC v1.0.0 beta Rev. 10 -- x86_64-Win64-win32/win64
| Windows 10 20H2 x86_64 | PID 16960
Unhandled exception: EZeroDivide: Floating point division by zero
  Stack trace:
  $00007FFEB2441F5A in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB2441E0E in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB24560B1 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB244B454 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB24560B1 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB24560B1 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB24528CE in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB24560B1 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB246712A in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB24560B1 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB2445732 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB245DA31 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB2460D78 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB245F6F9 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB24612B8 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB2462ECF in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB246AB9D in C:\Windows\System32\mfmp4srcsnk.dll

--------------- 31-10-2021, 11:53:18 ---------------
| DC v1.0.0 beta Rev. 10 -- x86_64-Win64-win32/win64
| Windows 10 20H2 x86_64 | PID 16960
Unhandled exception: EZeroDivide: Floating point division by zero
  Stack trace:
  $00007FFEB2441F5A in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB2441E0E in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB24560B1 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB244B454 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB24560B1 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB24560B1 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB24528CE in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB24560B1 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB246712A in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB24560B1 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB2445732 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB245DA31 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB2460D78 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB245F6F9 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB24612B8 in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB2462ECF in C:\Windows\System32\mfmp4srcsnk.dll
  $00007FFEB246AB9D in C:\Windows\System32\mfmp4srcsnk.dll

**Comment by alexx2000** [comment] 2021-10-31 11:52
Already fixed in DC [1.0.1](https://github.com/doublecmd/doublecmd/releases/tag/v1.0.1). Duplicate of #224.

**Closed by alexx2000** 2021-10-31 11:52 UTC
Labels: duplicate
