### ISSUE TITLE
Hourglass cursor shown indefinitely

### ISSUE THREAD

**Issue by Andreas0602** [doublecmd/doublecmd#699] opened 2022-12-04 11:25 UTC
### Version

Double Commander
Version: 1.1.0 alpha
Revision: 10491
Commit: 02a004568
Build date: 2022/12/03
Lazarus: 2.3.0.0
FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 13.0.1

### Description

Under macOS Ventura, Double Commander sometimes changes the mouse cursor to an hourglass for an "infinite" time (until you go to another directory). However, during that time, DC is actually not busy, but rather responsive. You can execute any action as usual, but with the mouse cursor being an hourglass, which is very irritating.

Steps to reproduce: Select a text file. Then press the F3 key to view it. Then press the Esc key to close the viewer. As a result, the mouse cursor will become an hourglass.

https://user-images.githubusercontent.com/79788982/205487704-a99faa85-8bbf-4ad2-942b-a484d6af36a0.mp4

**Comment by alexx2000** [comment] 2022-12-04 14:44
We can try to use Lazarus [new screen temporary cursor](https://wiki.lazarus.freepascal.org/Lazarus_2.2.0_release_notes#New_Screen_temporary_cursor)  API. Maybe it will work correctly.

**Comment by alexx2000** [comment] 2022-12-04 14:56
Try with revision 10496.

**Comment by Andreas0602** [comment] 2022-12-04 18:45
I've tried revision 10497, and unfortunately nothing has changed. The issue is still present.

**Comment by alexx2000** [comment] 2022-12-04 19:00
So it is a Lazarus LCLCocoa bug.
https://doublecmd.sourceforge.io/mantisbt/view.php?id=2409

**Comment by rich2014** [comment] 2022-12-06 14:54
maybe it's caused by background operations (related to threads)

**Comment by rich2014** [comment] 2022-12-22 09:34
it's the bug in Cocoa Interface.
fixed by #727.

**Comment by Andreas0602** [comment] 2022-12-22 10:25
Thank you very much, @rich2014 !

**Comment by rich2014** [comment] 2022-12-22 14:43
you are welcome @Andreas0602

**Closed** 2022-12-22 15:49 UTC
Labels: bug, macOS
