### ISSUE TITLE
Win10-64bit - Drag files outside DC -> Unspecified error

### ISSUE THREAD

**Issue by bazantm** [doublecmd/doublecmd#129] opened 2021-07-02 13:13 UTC
On version 0.9.10 (9640M) I get "Unspecified error" when dragging files or folders outside DC.

It happens on any file type (e. g. pdf, txt, docx) and I guess few days ago it worked fine. Restart of DC didnt help.

When dragging within the DC everything is fine.

**Comment by TheNicker** [comment] 2021-07-02 16:08
Many Drag&Drop issues has been fixed since 0.9. 
If your using windows, try to recreate it using the latest builds

**Comment by Skif-off** [comment] 2021-07-02 17:36
Official page for alpha version [here](https://doublecmd.sourceforge.io/site/rus/snapshots.php).
For Windows: download `doublecmd-1.0.0.rNNNN.i386-win32.7z` or `doublecmd-1.0.0.rNNNN.x86_64-win64.7z`, unpack and replace files in the current release.

**Comment by WhiteChairFromIkea** [comment] 2021-09-09 19:31
Update: It seems this is a problem with QT5 build only. I cannot reproduce with default build, but it is gard not to reproduce with QT5 snapshot... This drag and drop issue become a show stopper :/

```
Double Commander
Version: 1.0.0 alpha
Revision: 9925
Commit: b29a78521
Build date: 2021/09/05
Lazarus: 2.2.0.2
FPC: 3.0.4
Platform: x86_64-Win64-qt5
OS version: Windows 10 1809 x86_64

Widgetset library: Qt 5.13.0, libQt5Pas 5.6.1
```

**Comment by WhiteChairFromIkea** [comment] 2021-11-01 23:23
Maybe #239 is related to this (drag return to DC window). Sometimes, when returning drag from outside DC window, DC does not recognize that ole drag has been returned to DC window:

https://user-images.githubusercontent.com/46539653/139754472-d703695e-c81f-4689-a443-94801c500a2b.mp4

When this happens, status quo is kept for indefinite time until mouse is moved for some distance (random). Once mouse is started to move on top of DC window, lock down disappears, dragging status becomes valid: In case mouse button has been released during lock down period, `Result := DRAGDROP_S_DROP` is fired in `function TFileDropSource.QueryContinueDrag`, or mouse cursor is updated to correct icon, in case mouse button was not released.

**Comment by WhiteChairFromIkea** [comment] 2022-04-25 05:59
For everyone who uses dark (qt5) build and experiences dnd issue: It appears, that qt5 builds are superseded by native builds, which also supports dark mode. i feel no difference in "darkness" between qt5 and native ones. Please test non qt5 builds from now on: https://doublecmd.sourceforge.io/site/eng/snapshots.php. I did not get dnd problems so far, after a little bit of testing.

![5859b](https://user-images.githubusercontent.com/46539653/165029095-63ed928d-ffa4-4587-9f9a-546ced868ed6.png)

**Comment by WhiteChairFromIkea** [comment] 2022-04-26 12:57
@alexx2000 I suggest closing these, probably duplicates, and related only to qt5 builds:

https://github.com/doublecmd/doublecmd/issues/129
https://github.com/doublecmd/doublecmd/issues/229
https://github.com/doublecmd/doublecmd/issues/1

**Comment by WhiteChairFromIkea** [comment] 2022-04-29 06:35
I do confirm this is no longer an issue, testing after ~week of using: 
```
Double Commander
Version: 1.1.0 alpha
Revision: 10168
Commit: b657a2ce7
Build date: 2022/04/24
Lazarus: 2.2.0.4
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 Home 21H2 x86_64

```

**Comment by Gregory-K** [comment] 2022-05-11 15:58
Confirmed it's not an issue for

Double Commander  
```
Version: 1.1.0 alpha
Revision: 10177
Commit: 297693a4a
Build date: 2022/04/28
Lazarus: 2.2.0.4
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 21H1 x86_64
```

**Closed** 2022-12-14 18:16 UTC

**Comment by tucvbif** [comment] 2023-09-21 18:46
Issue is come back again
`Double Commander
Version: 1.1.2 beta
Revision: 71
Commit: 1c4639968
Build date: 2023/09/09
Lazarus: 2.2.7.0
FPC: 3.2.2
Platform: x86_64-Win64-win32/win64
OS version: Windows 10 1607 x86_64
`

**Comment by tucvbif** [comment] 2023-09-22 20:42
The issue is intermittent. Yesterday dragging didn't work, but today it's work again.
