### ISSUE TITLE
search in viewer miss highlight inverse background color 

### ISSUE THREAD

**Issue by cortopastito** [doublecmd/doublecmd#642] opened 2022-10-19 15:19 UTC
When I search for a word or select text in the viewer, it no longer has an inverse background color, which makes it very difficult to find the word you are looking for.
In previus versions search in viewer habe reverse background color. Please, put this functionality back.
I try changing the text and background colors in :settings->tools->viewer , but the viewer doesn't take those changes...

I use macos monterey : 12.6  and, double commander: doublecmd-1.1.0-10401.cocoa.x86_64

Thank you

![Captura de Pantalla 2022-10-19 a la(s) 11 52 08](https://user-images.githubusercontent.com/89138868/196733727-5c022089-f241-48b6-b8dc-07f1497642e1.png)

**Comment by alexx2000** [comment] 2022-10-19 15:35
It was never inverted color. DC use system `clHighlight `color. But for some reason it doesn't apply. Looks like Lazarus bug.

**Comment by Andreas0602** [comment] 2022-10-20 19:11
By the way, the problem (invisible selection of text) does occur regardless of whether the file is shown via the MacPreview plugin or as text.

**Comment by rich2014** [comment] 2022-10-21 05:34
something should be changed in Lazarus 2.3
will check it later

**Comment by rich2014** [comment] 2022-10-23 08:11
weirdly, using the version downloaded from snapshoots has this problem, but using the version compiled myself works fine.
it doesn't matter if Lazarus is the latest version in Git, or the September 17th version (8d06f23).
could this be a compilation problem?

**Comment by rich2014** [comment] 2022-10-23 08:12
<img width="652" alt="image" src="https://user-images.githubusercontent.com/102933068/197381601-4c8c7a55-c01f-45a7-acad-9165f8b3be69.png">
<img width="760" alt="image" src="https://user-images.githubusercontent.com/102933068/197381640-f9bc6b06-077f-4cb6-96d7-4c52142053fd.png">

**Comment by alexx2000** [comment] 2022-10-23 11:13
Sadly. I have no idea what can be wrong. So cross-compilation somehow affects it.

**Comment by Andreas0602** [comment] 2022-10-26 17:39
With the snapshot doublecmd-1.1.0-32f5996, the problem is fixed in the internal text viewer. Very good!

When the MacPreview plugin is activated, the problem still exists.

**Comment by rich2014** [comment] 2022-10-26 23:33
1. yes, it works.
2. MacPreview plugins doesn't support search text.
3. how was this version compiled? @alexx2000

**Comment by alexx2000** [comment] 2022-10-27 06:02
This version compiled using GitHub Actions (which use macOS 11). But GitHub Actions can use only released Lazarus version (2.2.2 in this case).

**Comment by Andreas0602** [comment] 2022-10-27 06:17
Even though the MacPreview plugin doesn't support search text, it would still be great if you could select text (and copy it and paste it elsewhere). This does not work.

When you invoke Preview from Finder, this does work.

**Comment by rich2014** [comment] 2022-10-27 14:37
> This version compiled using GitHub Actions (which use macOS 11). But GitHub Actions can use only released Lazarus version (2.2.2 in this case).

for further comparison, could you cross-compile the same version of DC with Lazarus 2.2.2?

**Comment by rich2014** [comment] 2022-10-27 14:45
> Even though the MacPreview plugin doesn't support search text, it would still be great if you could select text (and copy it and paste it elsewhere). This does not work.
> 
> When you invoke Preview from Finder, this does work.

it's seems that copy disabled  in QLPreviewView, and enabled in QLPreviewPanel.
but QLPreviewPanel is an independent window and cannot be seamlessly integrated with DC's QuickView/View.

**Comment by rich2014** [comment] 2022-10-29 00:49
doublecmd-1.1.0-10406.cocoa.aarch64 works fine

**Comment by Andreas0602** [comment] 2022-10-29 09:20
doublecmd-1.1.0-10406.cocoa.x86_64 also works fine for me.

The non-working selection and copying of text in the MacPreview plugin may indeed be a separate problem. Maybe this has never worked. The plugin is quite new, and I didn't test it thoroughly in the past. Meanwhile I've set the DetectString of this plugin to (EXT!="txt"), so that it won't be used for txt files.

**Comment by alexx2000** [comment] 2022-10-29 09:57
> doublecmd-1.1.0-10406.cocoa.aarch64 works fine

It's cross-compiled using Lazarus 2.2.2. So problem only exists when DC cross-compiled using Lazarus 2.3.

**Comment by rich2014** [comment] 2022-10-29 11:05
> > doublecmd-1.1.0-10406.cocoa.aarch64 works fine
> 
> It's cross-compiled using Lazarus 2.2.2. So problem only exists when DC cross-compiled using Lazarus 2.3.

it looks like that, but it's unbelievable.
maybe there is something missing.

**Comment by alexx2000** [comment] 2022-10-30 10:59
Yes, it is a strange.
I cross-compiled doublecmd-1.1.0-10408 using Lazarus 2.2.4 and it has this problem too.

**Comment by alexx2000** [comment] 2022-11-17 19:16
I created GitHub action which compile Lazarus 2.3 from git at first step and build snapshot at second step.

**Closed by alexx2000** 2022-11-17 19:16 UTC
