### ISSUE TITLE
Drag and Drop issue, first time it works, second time doesn't work as expected

### ISSUE THREAD

**Issue by LifeTimeCoder** [doublecmd/doublecmd#331] opened 2022-01-20 16:13 UTC
Interesting issue that D&D is not working on second time. here is repro in v1.0.3.

Open VLC media player or other player. 
drag and drop a video file from DblCmd into the player... it works.. plays the video .. perfect!
while the player is playing, drag and drop another video into the player to replace what is playing.. **DblCmd takes its time** and **displays copy window** for copying a file.

**Comment by j2969719** [comment] 2022-01-20 16:22
F1 > copy to clipboard

**Comment by LifeTimeCoder** [comment] 2022-01-20 16:46
Double Commander
Version: 1.0.3 beta
Revision: 68
Commit: b3740938d
Build date: 2022/01/07
Lazarus: 2.2.0.3
FPC: 3.2.2
Platform: x86_64-Win64-qt5
OS version: Windows 10 21H2 x86_64

Widgetset library: Qt 5.13.0, libQt5Pas 5.6.1

**Comment by WhiteChairFromIkea** [comment] 2022-01-20 16:51
This is a duplicate of https://github.com/doublecmd/doublecmd/issues/129

This problem is a showstopper for qt5 build 😕

**Comment by alexx2000** [comment] 2022-08-11 05:41
Qt version is not build anymore. Use normal version instead.
https://github.com/doublecmd/doublecmd/issues/451#issuecomment-1148864940

**Closed by alexx2000** 2022-08-11 05:41 UTC
