### ISSUE TITLE
[Bug][Beta]  Linux tar.bz2 unpack fails

### ISSUE THREAD

**Issue by pwn0r** [doublecmd/doublecmd#355] opened 2022-02-15 15:17 UTC
Linux version of doublecmd cannot unpack a tar.bz2 archive. Generates a range check error.  Happens every time for me. 
as an example of such archive try 
from e.g. _www.mozilla.org/en-US/firefox/all/#product-desktop-beta_ select Linux 64bit 

not a new problem, confirmed now for 1.04 but it did exist before, in 1.03, 1.02 etc beta versions. 
I have a few VMs running ubuntu 21.04 LTS or Debian11. I use a repository from opensuse to autoupdate doublecmd, as native repositories are outdated.

**Comment by JonnyTech** [comment] 2022-02-15 15:37
I can confirm. Just download and tried extracting. It always errors on a file:

```
Range check error

firefox/omni.ja
```

Pressing `ignore` keeps showing errors which I have to keep ignoring.

Here is my terminal output:

```
$ doublecmd 
SystemLocale en_GB
SystemLanguage en
SystemEncoding UTF-8
DefaultSystemCodePage 65001
DefaultFileSystemCodePage 65001
DefaultRTLFileSystemCodePage 65001
XInitThreads: 1
Starting GuiMessageQueue
Starting Double Commander
Double Commander 1.0.4 beta
Revision: 84
Commit: a1d58d4dd
Build: 2022/02/05
Lazarus: 2.0.12.0
Free Pascal: 3.2.0
Platform: x86_64-Linux-gtk2
System: MX 21 Wildflower
Desktop Environment: Xfce
Widgetset library: GTK 2.24.33
This program is free software released under terms of GNU GPL 2
(C)opyright 2006-2022 Alexander Koblov (alexx2000@mail.ru)
   and contributors (see about dialog)
Executable directory: /usr/lib/doublecmd/
Loading configuration from /home/user/.config/doublecmd/
Loading lng file: /usr/lib/doublecmd/language/doublecmd.en.po
Error loading configuration file /home/user/.config/doublecmd/favoritetabs.xml
PollThread: Start polling
PollThread: AddPoll 11
Creating PixmapManager
Loading icon theme DCTheme
Loading icon theme DCTheme
Error: pixmap [/usr/lib/doublecmd/doublecmd] not loaded!
TColumnsFileView.Create components
Creating TFileSystemFileSource
TColumnsFileView.Create components
PollThread: AddPoll 20
UDev: Begin monitoring
FileSystemWatcher thread starting
Detecting mounts through /proc/self/mounts
PollThread: AddPoll 21
frmMain.frmMainShow
Error loading configuration file /home/user/.config/doublecmd/highlighters.xml

(doublecmd:26088): GLib-GObject-WARNING **: 15:29:03.897: ../../../gobject/gsignal.c:1279: no emission of signal "key-release-event" to stop for instance '0x364d820'
Creating TWcxArchiveFileSource
SystemLocale en_GB
SystemLanguage en
SystemEncoding UTF-8
DefaultSystemCodePage 65001
DefaultFileSystemCodePage 65001
DefaultRTLFileSystemCodePage 65001
Zip plugin is loaded
WCX module loaded %commander_path%/plugins/wcx/zip/zip.wcx at 0000000003880C60
Open Archive
Get File List
Creating connection TWcxArchiveFileSourceConnection
Creating connection TWcxArchiveFileSourceConnection
Creating connection TWcxArchiveFileSourceConnection
Creating connection TWcxArchiveFileSourceConnection
Found registered plugin %commander_path%/plugins/wcx/zip/zip.wcx for archive /home/user/Downloads/firefox-97.0.tar.bz2
Creating connection TWcxArchiveFileSourceConnection
Destroying connection TWcxArchiveFileSourceConnection

(doublecmd:26088): GLib-CRITICAL **: 15:32:25.983: Source ID 285 was not found when attempting to remove it

(doublecmd:26088): GLib-CRITICAL **: 15:32:25.983: Source ID 286 was not found when attempting to remove it
Waiting for FileSystemWatcher thread
FileSystemWatcher thread finished
FileSystemWatcher thread starting
Process 26472 finished, exit status 0
```
Once all files are extracted then they work correctly - I managed to run the new `./firefox` without issue.

**Comment by alexx2000** [comment] 2022-02-15 16:03
I cannot reproduce. Works fine for me.

**Comment by JonnyTech** [comment] 2022-02-15 16:27
@alexx2000  I have replicated on two computers running MX Linux 21 (based on Debian 11 Bullseye Stable) 64bit:

```
uname -a
Linux WOPR 5.16.0-1mx-amd64 #1 SMP PREEMPT Debian 5.16.7-2~mx21+1 (2022-02-09) x86_64 GNU/Linux
```

Double Commander installed from https://download.opensuse.org/repositories/home:/Alexx2000/Debian_11/

Did you wait for the extraction to complete? It does not happen until over 50% extracted.

Are any logs generated that I can look at?

**Comment by alexx2000** [comment] 2022-02-15 16:53
Yes, I extracted the whole archive. Your console output does not have any error. I guess something wrong happen in the Zip plugin but such errors is not logged. Do you have enough space in the TEMP directory?

**Comment by pwn0r** [comment] 2022-02-15 17:07
in my case on ubuntu 20.04.3: 

<pre>Linux version 5.13.0-28-generic (buildd@lgw01-amd64-035) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022
</pre>

**Comment by JonnyTech** [comment] 2022-02-15 18:37
> Do you have enough space in the TEMP directory?

Yes, I thought that too but there is Gb's of space. Also tried drive to other drive with separate drive for TMP and still get message.

**Comment by j2969719** [comment] 2022-02-16 06:45
firefox-98.0b5.tar.bz2 unpacks without any issues for me, but i noticed that the dates in the filelist are not correct

**Comment by alexx2000** [comment] 2022-02-16 15:50
This archive stores time in the PAX header. I added reading the time from there.

@pwn0r , what time zone do you have?

**Comment by pwn0r** [comment] 2022-02-18 00:28
> 

i run a few VMs on european servers. Time is automatic but timezone is manually set to GMT for simplicity.

**Comment by JonnyTech** [comment] 2022-11-24 21:58
I am getting another `Range check error` `unknown` error, this time when trying to extract a file from a `.gz` archive:

![image](https://user-images.githubusercontent.com/3584732/203865840-776b5b33-6596-4a24-a6af-561bb1bb74c4.png)

Using `PeaZip` extracts files correctly, and so does using `gzip` from the command line:

```
$ gzip -dfkv db.gz 
db.gz:	 88.8% -- created db
```

This is the DC log:

```
$ doublecmd 
SystemLocale en_GB
SystemLanguage en
SystemEncoding UTF-8
DefaultSystemCodePage 65001
DefaultFileSystemCodePage 65001
DefaultRTLFileSystemCodePage 65001
Starting GuiMessageQueue
Starting Double Commander
Double Commander 1.0.8
Revision: 191
Commit: ee1f44b3c
Build: 2022/09/18
Lazarus: 2.2.2.0
Free Pascal: 3.2.2
Platform: x86_64-Linux-qt5
System: MX 21.2.1 Wildflower
Desktop Environment: Xfce
Widgetset library: Qt 5.15.2, libQt5Pas 5.6.1
This program is free software released under terms of GNU GPL 2
(C)opyright 2006-2022 Alexander Koblov (alexx2000@mail.ru)
   and contributors (see about dialog)
Executable directory: /usr/lib/doublecmd/
Loading configuration from /home/user/.config/doublecmd/
Loading lng file: /usr/lib/doublecmd/language/doublecmd.en.po
Error loading configuration file /home/user/.config/doublecmd/favoritetabs.xml
PollThread: Start polling
PollThread: AddPoll 20
Creating PixmapManager
Loading icon theme Papirus
Loading icon theme Breeze
Loading icon theme Hicolor
Loading icon theme DCTheme
Loading icon theme DCTheme
TColumnsFileView.Create components
Creating TFileSystemFileSource
TColumnsFileView.Create components
PollThread: AddPoll 28
UDev: Begin monitoring
FileSystemWatcher thread starting
Detecting mounts through /proc/self/mounts
PollThread: AddPoll 29
Error loading configuration file /home/user/.config/doublecmd/highlighters.xml
frmMain.frmMainShow
Creating TWcxArchiveFileSource
SystemLocale en_GB
SystemLanguage en
SystemEncoding UTF-8
DefaultSystemCodePage 65001
DefaultFileSystemCodePage 65001
DefaultRTLFileSystemCodePage 65001
Zip plugin is loaded
WCX module loaded %commander_path%/plugins/wcx/zip/zip.wcx at 0000000001CB0F00
Open Archive
Get File List
Creating connection TWcxArchiveFileSourceConnection
Creating connection TWcxArchiveFileSourceConnection
Creating connection TWcxArchiveFileSourceConnection
Creating connection TWcxArchiveFileSourceConnection
Found registered plugin %commander_path%/plugins/wcx/zip/zip.wcx for archive /tmp/blah/db.gz
Creating connection TWcxArchiveFileSourceConnection
Destroying connection TWcxArchiveFileSourceConnection
```

Now the error is on screen.
If I press `retry` a few times, the error is logged and the message pops up again:

```
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2181, resource id: 23472061, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2360, resource id: 23480648, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2497, resource id: 23481536, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2634, resource id: 23482146, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2775, resource id: 23482747, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2914, resource id: 23483319, major code: 40 (TranslateCoords), minor code: 0
```

Then I press `ignore`:

```
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 6217, resource id: 23483901, major code: 40 (TranslateCoords), minor code: 0
```

Here is my system details:

```
Double Commander
Version: 1.0.8
Revision: 191
Commit: ee1f44b3c
Build date: 2022/09/18
Lazarus: 2.2.2.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: MX 21.2.1 Wildflower

Widgetset library: Qt 5.15.2, libQt5Pas 5.6.1
```

Just in case you think that it is an issue with the `qt` build, I then tried with the latest `gtk` .AppImage:

```
$ ./doublecmd-gtk-1.0.8-2.1.Build2.2.glibc2.10-x86_64.AppImage 
SystemLocale en_GB
SystemLanguage en
SystemEncoding UTF-8
DefaultSystemCodePage 65001
DefaultFileSystemCodePage 65001
DefaultRTLFileSystemCodePage 65001
XInitThreads: 1
Starting GuiMessageQueue
Starting Double Commander
Double Commander 1.0.8
Revision: 191
Commit: ee1f44b3c
Build: 2022/09/18
Lazarus: 2.2.2.0
Free Pascal: 3.2.2
Platform: x86_64-Linux-gtk2
System: MX 21.2.1 Wildflower
Desktop Environment: Xfce
Widgetset library: GTK 2.24.33
This program is free software released under terms of GNU GPL 2
(C)opyright 2006-2022 Alexander Koblov (alexx2000@mail.ru)
   and contributors (see about dialog)
Executable directory: /tmp/.mount_doubleog364S/usr/lib64/doublecmd/
Loading configuration from /home/user/.config/doublecmd/
Error loading configuration file /home/user/.config/doublecmd/favoritetabs.xml
PollThread: Start polling
PollThread: AddPoll 12
Creating PixmapManager
Loading icon theme DCTheme
Loading icon theme DCTheme
Error: pixmap [/tmp/.mount_doubleog364S/usr/lib64/doublecmd/doublecmd] not loaded!
TColumnsFileView.Create components
Creating TFileSystemFileSource
TColumnsFileView.Create components
PollThread: AddPoll 21
UDev: Begin monitoring
FileSystemWatcher thread starting
Detecting mounts through /proc/self/mounts
PollThread: AddPoll 22
Error loading configuration file /home/user/.config/doublecmd/highlighters.xml
frmMain.frmMainShow
Creating TWcxArchiveFileSource
SystemLocale en_GB
SystemLanguage en
SystemEncoding UTF-8
DefaultSystemCodePage 65001
DefaultFileSystemCodePage 65001
DefaultRTLFileSystemCodePage 65001
Zip plugin is loaded
WCX module loaded %commander_path%/plugins/wcx/zip/zip.wcx at 0000000002085670
Open Archive
Get File List
Creating connection TWcxArchiveFileSourceConnection
Creating connection TWcxArchiveFileSourceConnection
Creating connection TWcxArchiveFileSourceConnection
Creating connection TWcxArchiveFileSourceConnection
Found registered plugin %commander_path%/plugins/wcx/zip/zip.wcx for archive /tmp/blah/db.gz
Creating connection TWcxArchiveFileSourceConnection
Destroying connection TWcxArchiveFileSourceConnection

(doublecmd:7997): GLib-CRITICAL **: 21:48:16.172: Source ID 277 was not found when attempting to remove it

(doublecmd:7997): GLib-CRITICAL **: 21:48:16.172: Source ID 278 was not found when attempting to remove it
Saving configuration
PollThread: RemovePoll 12
PollThread: AddPoll 12
Finished Double Commander
Destroying main form
Drive watcher finished
Waiting for FileSystemWatcher thread
FileSystemWatcher thread finished
Main form destroyed
Waiting for workers thread 00000000025A9F78
Finalized workers thread   00000000025A9F78
Waiting for workers thread 00000000025A9658
Finalized workers thread   00000000025A9658
Destroying TWcxArchiveFileSource when refcount=0
Destroying TFileSystemFileSource when refcount=0
Finishing GuiMessageQueue
Destroying connection TWcxArchiveFileSourceConnection
Destroying connection TWcxArchiveFileSourceConnection
Destroying connection TWcxArchiveFileSourceConnection
Destroying connection TWcxArchiveFileSourceConnection
PollThread: RemovePoll 12
PollThread: Finish polling
Shutting down PixmapManager
TServerListnerThread.Destroy
```

Same error message, but console shows the `GLib-CRITICAL` errors (I pressed `ignore` at the error dialog).

If you would like a file that exhibits the problem then I can send it to you but I cannot share it here as it contains sensitive data.

**Comment by alexx2000** [comment] 2022-11-25 18:15
> If you would like a file that exhibits the problem then I can send it to you but I cannot share it here as it contains sensitive data.

Yes, I need a file that exhibits the problem.

**Comment by JonnyTech** [comment] 2022-11-25 19:44
Thanks @alexx2000, email sent to the address on your profile page.

**Comment by alexx2000** [comment] 2022-12-05 16:31
I hope it fixed now (revision 10501).

**Comment by JonnyTech** [comment] 2022-12-05 22:54
Wow, excellent, you done it, fantastic work @alexx2000, thank you very much indeed!

**Closed** 2023-01-21 08:46 UTC
